NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.pueblo3.hispania.es-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.pueblo3.hispania.es-cert.pem
    OrganizationalUnitIdentifier: peer
