NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.pueblo1.hispania.es-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.pueblo1.hispania.es-cert.pem
    OrganizationalUnitIdentifier: peer
