# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    #image: hyperledger/fabric-orderer:$IMAGE_TAG
    image: hyperledger/fabric-orderer:1.4.2
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      
  peer0.pueblo1.hispania.es:
    container_name: peer0.pueblo1.hispania.es
    extends:
      file: peer-base.yaml
      service: peer-base
    # dns_search: .
    environment:
      - CORE_PEER_ID=peer0.pueblo1.hispania.es
      - CORE_PEER_ADDRESS=peer0.pueblo1.hispania.es:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pueblo1.hispania.es:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pueblo1.hispania.es/peers/peer0.pueblo1.hispania.es/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pueblo1.hispania.es/peers/peer0.pueblo1.hispania.es/tls:/etc/hyperledger/fabric/tls
        - peer0.pueblo1.hispania.es:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.pueblo1.hispania.es:
    container_name: peer1.pueblo1.hispania.es
    extends:
      file: peer-base.yaml
      service: peer-base
    dns_search: .
    environment:
      - CORE_PEER_ID=peer0.pueblo2.hispania.es
      - CORE_PEER_ADDRESS=peer1.pueblo1.hispania.es:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pueblo2.hispania.es:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pueblo1.hispania.es:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:6984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pueblo2.hispania.es/peers/peer0.pueblo2.hispania.es/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pueblo2.hispania.es/peers/peer0.pueblo2.hispania.es/tls:/etc/hyperledger/fabric/tls
        - peer0.pueblo2.hispania.es:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  peer0.pueblo2.hispania.es:
    container_name: peer0.pueblo2.hispania.es
    extends:
      file: peer-base.yaml
      service: peer-base
    dns_search: .
    environment:
      - CORE_PEER_ID=peer0.pueblo2.hispania.es
      - CORE_PEER_ADDRESS=peer0.pueblo2.hispania.es:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pueblo2.hispania.es:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pueblo1.hispania.es:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:6984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pueblo2.hispania.es/peers/peer0.pueblo2.hispania.es/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pueblo2.hispania.es/peers/peer0.pueblo2.hispania.es/tls:/etc/hyperledger/fabric/tls
        - peer0.pueblo2.hispania.es:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
  
  peer0.pueblo3.hispania.es:
    container_name: peer0.pueblo3.hispania.es
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.pueblo3.hispania.es
      - CORE_PEER_ADDRESS=peer0.pueblo3.hispania.es:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pueblo3.hispania.es:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pueblo1.hispania.es:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:7984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pueblo3.hispania.es/peers/peer0.pueblo3.hispania.es/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pueblo3.hispania.es/peers/peer0.pueblo3.hispania.es/tls:/etc/hyperledger/fabric/tls
        - peer0.pueblo3.hispania.es:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053